import type { NextConfig } from "next";

const legacyRedirects = [
  ["sales", "main-menu/sales"],
  ["quotation", "main-menu/sales/quotation"],
  ["addQuotation", "main-menu/sales/quotation/add"],
  ["saleOrder", "main-menu/sales/sale-order"],
  ["addSaleOrder", "main-menu/sales/sale-order/add"],
  ["salesInvoice", "main-menu/sales/sales-invoice"],
  ["addSalesInvoice", "main-menu/sales/sales-invoice/add"],
  ["paymentIn", "main-menu/sales/payment-in"],
  ["addPaymentIn", "main-menu/sales/payment-in/add"],
  ["salesReturn", "main-menu/sales/sales-return"],
  ["addSalesReturn", "main-menu/sales/sales-return/add"],
  ["deliveryNote", "main-menu/sales/delivery-note"],
  ["addDeliveryNote", "main-menu/sales/delivery-note/add"],
  ["purchase", "main-menu/purchase"],
  ["purchaseOrder", "main-menu/purchase/purchase-order"],
  ["addPurchaseOrder", "main-menu/purchase/purchase-order/add"],
  ["purchaseBill", "main-menu/purchase/purchase-bill"],
  ["addPurchaseBill", "main-menu/purchase/purchase-bill/add"],
  ["paymentOut", "main-menu/purchase/payment-out"],
  ["addPaymentOut", "main-menu/purchase/payment-out/add"],
  ["purchaseReturn", "main-menu/purchase/purchase-return"],
  ["addPurchaseReturn", "main-menu/purchase/purchase-return/add"],
  ["cashBank", "main-menu/cash-bank"],
  ["bankAccount", "main-menu/cash-bank/bank-account"],
  ["addBankAccount", "main-menu/cash-bank/bank-account/add"],
  ["cashInHand", "main-menu/cash-bank/cash-in-hand"],
  ["cheque", "main-menu/cash-bank/cheque"],
  ["bankToCashTransfer", "main-menu/cash-bank/bank-to-cash"],
  ["bankToBankTransfer", "main-menu/cash-bank/bank-to-bank"],
  ["cashToBankTransfer", "main-menu/cash-bank/cash-to-bank"],
  ["adjustBankBalance", "main-menu/cash-bank/adjust-balance"],
  ["loanAmount", "main-menu/cash-bank/loan-amount"],
  ["party", "main-menu/party"],
  ["addParty", "main-menu/party/add"],
  ["employee", "main-menu/employee"],
  ["addEmployee", "main-menu/employee/add"],
  ["expense", "main-menu/expense"],
  ["addExpense", "main-menu/expense/add"],
  ["itemManagement", "main-menu/items"],
  ["addProduct", "main-menu/items/add-product"],
  ["addManufacturing", "main-menu/items/add-manufacturing"],
  ["addService", "main-menu/items/add-service"],
  ["addCategory", "main-menu/items/add-category"],
  ["addUnit", "main-menu/items/add-unit"],
  ["setConversion", "main-menu/items/set-conversion"],
  ["utilities", "main-menu/utilities"],
  ["importParty", "main-menu/utilities/import-party"],
  ["importExpense", "main-menu/utilities/import-expense"],
  ["importItem", "main-menu/utilities/import-item"],
  ["importBillbook", "main-menu/utilities/import-billbook"],
  ["recycleBin", "main-menu/utilities/recycle-bin"],
  ["closingFinancialYears", "main-menu/utilities/closing-financial-years"],
  ["settings", "main-menu/settings"],
  ["generalSettings", "main-menu/settings/general"],
  ["transactionSettings", "main-menu/settings/transaction"],
  ["invoicePrint", "main-menu/settings/invoice-print"],
  ["taxes", "main-menu/settings/taxes"],
  ["reminders", "main-menu/settings/reminders"],
  ["itemSettings", "main-menu/settings/item"],
  ["partySettings", "main-menu/settings/party"],
  ["businessDetail", "main-menu/business-detail"],
  ["profileDetail", "main-menu/profile-detail"],
  ["userManagement", "main-menu/user-management"],
  ["otherIncome", "main-menu/other-income"],
  ["marketing", "main-menu/marketing"],
  ["backUpAndRestore", "main-menu/backup-and-restore"],
  ["calendar", "main-menu/calendar"],
  ["addEventScreen", "main-menu/calendar/add"],
  ["updateEventScreen", "main-menu/calendar/update"],
  ["plansAndPricing", "main-menu/plans-and-pricing"],
  ["posList", "main-menu/pos"],
  ["pos", "main-menu/pos/terminal"],
  ["posBill", "main-menu/pos/bill"],
].map(([source, destination]) => ({
  source: `/${source}`,
  destination: `/${destination}`,
  permanent: false,
}));

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "i.pravatar.cc",
      },
    ],
  },
  async redirects() {
    return legacyRedirects;
  },
};

export default nextConfig;
